import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FirebaseProvidder } from "@/components/providers/firebase-provider";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import { PropsWithChildren } from "react";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen")}>
        <ReactQueryProvider>
          <FirebaseProvidder>{props.children}</FirebaseProvidder>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
